# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1997, 1442)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setHorizontalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.log_textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.log_textBrowser.setEnabled(True)
        self.log_textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.log_textBrowser.setObjectName("log_textBrowser")
        self.gridLayout_6.addWidget(self.log_textBrowser, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.initialization = QtWidgets.QGroupBox(self.tab)
        self.initialization.setObjectName("initialization")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.initialization)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.plot_initial_widget = MplWidget(self.initialization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_initial_widget.sizePolicy().hasHeightForWidth())
        self.plot_initial_widget.setSizePolicy(sizePolicy)
        self.plot_initial_widget.setObjectName("plot_initial_widget")
        self.gridLayout_4.addWidget(self.plot_initial_widget, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.initialization, 2, 0, 1, 1)
        self.froce_groupBox = QtWidgets.QGroupBox(self.tab)
        self.froce_groupBox.setObjectName("froce_groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.froce_groupBox)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.comboBox = QtWidgets.QComboBox(self.froce_groupBox)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_7.addWidget(self.comboBox, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.froce_groupBox)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 4, 2, 1, 1)
        self.plot_force_widget = MplWidget(self.froce_groupBox)
        self.plot_force_widget.setObjectName("plot_force_widget")
        self.gridLayout_7.addWidget(self.plot_force_widget, 5, 0, 1, 3)
        self.gridLayout_3.addWidget(self.froce_groupBox, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem2, 0, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setRowStretch(2, 999)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWidget_namelist = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_namelist.setObjectName("tableWidget_namelist")
        self.tableWidget_namelist.setColumnCount(0)
        self.tableWidget_namelist.setRowCount(0)
        self.gridLayout_5.addWidget(self.tableWidget_namelist, 2, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_5.addWidget(self.textBrowser, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox_maxDoms = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_maxDoms.setObjectName("comboBox_maxDoms")
        self.horizontalLayout.addWidget(self.comboBox_maxDoms)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButton_Reset = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Reset.setObjectName("pushButton_Reset")
        self.horizontalLayout.addWidget(self.pushButton_Reset)
        self.pushButton_validate = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_validate.setObjectName("pushButton_validate")
        self.horizontalLayout.addWidget(self.pushButton_validate)
        self.gridLayout_5.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem4, 0, 0, 1, 1)
        self.gridLayout_5.setRowStretch(2, 9999)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_9.addWidget(self.label_14, 10, 0, 1, 1)
        self.pushButton_ideal_folder = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_ideal_folder.setObjectName("pushButton_ideal_folder")
        self.gridLayout_9.addWidget(self.pushButton_ideal_folder, 3, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout_9.addWidget(self.label_12, 9, 0, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_9.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 8, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_9.addWidget(self.label_3, 2, 0, 1, 1)
        self.pushButton_input_soil_folder = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_input_soil_folder.setObjectName("pushButton_input_soil_folder")
        self.gridLayout_9.addWidget(self.pushButton_input_soil_folder, 6, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_9.addWidget(self.label_5, 6, 0, 1, 1)
        self.pushButton_input_sounding_folder = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_input_sounding_folder.setObjectName("pushButton_input_sounding_folder")
        self.gridLayout_9.addWidget(self.pushButton_input_sounding_folder, 7, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setObjectName("label_6")
        self.gridLayout_9.addWidget(self.label_6, 1, 0, 1, 3)
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 4, 0, 1, 3)
        self.lineEdit_wrf_out_folder = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_wrf_out_folder.setEnabled(False)
        self.lineEdit_wrf_out_folder.setObjectName("lineEdit_wrf_out_folder")
        self.gridLayout_9.addWidget(self.lineEdit_wrf_out_folder, 15, 1, 1, 1)
        self.lineEdit_input_soil_folder = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_input_soil_folder.setEnabled(False)
        self.lineEdit_input_soil_folder.setObjectName("lineEdit_input_soil_folder")
        self.gridLayout_9.addWidget(self.lineEdit_input_soil_folder, 6, 1, 1, 1)
        self.lineEdit_wrf_folder = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_wrf_folder.setEnabled(False)
        self.lineEdit_wrf_folder.setObjectName("lineEdit_wrf_folder")
        self.gridLayout_9.addWidget(self.lineEdit_wrf_folder, 2, 1, 1, 1)
        self.lineEdit_force_ideal_folder = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_force_ideal_folder.setEnabled(False)
        self.lineEdit_force_ideal_folder.setObjectName("lineEdit_force_ideal_folder")
        self.gridLayout_9.addWidget(self.lineEdit_force_ideal_folder, 8, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 5, 0, 1, 3)
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 15, 0, 1, 1)
        self.lineEdit_input_sounding_folder = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_input_sounding_folder.setEnabled(False)
        self.lineEdit_input_sounding_folder.setObjectName("lineEdit_input_sounding_folder")
        self.gridLayout_9.addWidget(self.lineEdit_input_sounding_folder, 7, 1, 1, 1)
        self.pushButton_wrf_out_folder = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_wrf_out_folder.setObjectName("pushButton_wrf_out_folder")
        self.gridLayout_9.addWidget(self.pushButton_wrf_out_folder, 15, 2, 1, 1)
        self.lineEdit_ideal_folder = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_ideal_folder.setEnabled(False)
        self.lineEdit_ideal_folder.setObjectName("lineEdit_ideal_folder")
        self.gridLayout_9.addWidget(self.lineEdit_ideal_folder, 3, 1, 1, 1)
        self.pushButton_force_ideal_folder = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_force_ideal_folder.setObjectName("pushButton_force_ideal_folder")
        self.gridLayout_9.addWidget(self.pushButton_force_ideal_folder, 8, 2, 1, 1)
        self.pushButton_wrf_folder = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_wrf_folder.setObjectName("pushButton_wrf_folder")
        self.gridLayout_9.addWidget(self.pushButton_wrf_folder, 2, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_9.addWidget(self.label_13, 14, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_9.addWidget(self.label_15, 11, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.gridLayout_9.addWidget(self.label_16, 12, 0, 1, 1)
        self.lineEdit_namelist_input_folder = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_namelist_input_folder.setEnabled(False)
        self.lineEdit_namelist_input_folder.setObjectName("lineEdit_namelist_input_folder")
        self.gridLayout_9.addWidget(self.lineEdit_namelist_input_folder, 11, 1, 1, 1)
        self.pushButton_namelist_input_folder = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_namelist_input_folder.setObjectName("pushButton_namelist_input_folder")
        self.gridLayout_9.addWidget(self.pushButton_namelist_input_folder, 11, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.gridLayout_9.addWidget(self.label_17, 16, 0, 1, 1)
        self.pushButton_run_scm_wrf = QtWidgets.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_run_scm_wrf.setFont(font)
        self.pushButton_run_scm_wrf.setObjectName("pushButton_run_scm_wrf")
        self.gridLayout_9.addWidget(self.pushButton_run_scm_wrf, 17, 0, 1, 3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem5, 0, 0, 1, 1)
        self.textBrowser_wrf_out = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_wrf_out.setObjectName("textBrowser_wrf_out")
        self.gridLayout_9.addWidget(self.textBrowser_wrf_out, 19, 0, 1, 3)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_8.addWidget(self.label_18, 0, 0, 1, 1)
        self.pushButton_wrf_run_log_clear = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_wrf_run_log_clear.setObjectName("pushButton_wrf_run_log_clear")
        self.gridLayout_8.addWidget(self.pushButton_wrf_run_log_clear, 0, 1, 1, 1)
        self.gridLayout_8.setColumnStretch(0, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 18, 0, 1, 3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_12.addWidget(self.label_20, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem6, 0, 2, 1, 1)
        self.comboBox_N2 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_N2.setObjectName("comboBox_N2")
        self.gridLayout_12.addWidget(self.comboBox_N2, 0, 1, 1, 1)
        self.widget_N2 = MplWidget(self.tab_4)
        self.widget_N2.setObjectName("widget_N2")
        self.gridLayout_12.addWidget(self.widget_N2, 1, 0, 1, 3)
        self.gridLayout_11.addLayout(self.gridLayout_12, 0, 1, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        self.label_21.setObjectName("label_21")
        self.gridLayout_13.addWidget(self.label_21, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem7, 0, 2, 1, 1)
        self.comboBox_N3 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_N3.setObjectName("comboBox_N3")
        self.gridLayout_13.addWidget(self.comboBox_N3, 0, 1, 1, 1)
        self.widget_N3 = MplWidget(self.tab_4)
        self.widget_N3.setObjectName("widget_N3")
        self.gridLayout_13.addWidget(self.widget_N3, 1, 0, 1, 3)
        self.gridLayout_11.addLayout(self.gridLayout_13, 1, 0, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_22 = QtWidgets.QLabel(self.tab_4)
        self.label_22.setObjectName("label_22")
        self.gridLayout_14.addWidget(self.label_22, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem8, 0, 2, 1, 1)
        self.comboBox_N4 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_N4.setObjectName("comboBox_N4")
        self.gridLayout_14.addWidget(self.comboBox_N4, 0, 1, 1, 1)
        self.widget_N4 = MplWidget(self.tab_4)
        self.widget_N4.setObjectName("widget_N4")
        self.gridLayout_14.addWidget(self.widget_N4, 1, 0, 1, 3)
        self.gridLayout_11.addLayout(self.gridLayout_14, 1, 1, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setObjectName("label_19")
        self.gridLayout_10.addWidget(self.label_19, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem9, 0, 2, 1, 1)
        self.comboBox_N1 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_N1.setObjectName("comboBox_N1")
        self.gridLayout_10.addWidget(self.comboBox_N1, 0, 1, 1, 1)
        self.widget_N1 = MplWidget(self.tab_4)
        self.widget_N1.setObjectName("widget_N1")
        self.gridLayout_10.addWidget(self.widget_N1, 1, 0, 1, 3)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.setRowStretch(0, 5)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.comboBox)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "User Hint"))
        self.initialization.setTitle(_translate("MainWindow", "input_souding_soil"))
        self.froce_groupBox.setTitle(_translate("MainWindow", "force_ideal.nc"))
        self.comboBox.setItemText(0, _translate("MainWindow", "U"))
        self.comboBox.setItemText(1, _translate("MainWindow", "V"))
        self.comboBox.setItemText(2, _translate("MainWindow", "W"))
        self.comboBox.setItemText(3, _translate("MainWindow", "QVAPOR"))
        self.comboBox.setItemText(4, _translate("MainWindow", "QCLOUD"))
        self.comboBox.setItemText(5, _translate("MainWindow", "QRAIN"))
        self.comboBox.setItemText(6, _translate("MainWindow", "theta"))
        self.label.setText(_translate("MainWindow", "variable:"))
        self.pushButton.setText(_translate("MainWindow", "column.xml"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Input"))
        self.label_2.setText(_translate("MainWindow", "Number of Domains(max_dom):"))
        self.pushButton_Reset.setText(_translate("MainWindow", "Reset"))
        self.pushButton_validate.setText(_translate("MainWindow", "Validate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "NameList"))
        self.label_14.setText(_translate("MainWindow", "config foloer"))
        self.pushButton_ideal_folder.setText(_translate("MainWindow", "..."))
        self.label_7.setText(_translate("MainWindow", "input_sounding"))
        self.label_8.setText(_translate("MainWindow", "force_ideal"))
        self.label_4.setText(_translate("MainWindow", "ideal"))
        self.label_3.setText(_translate("MainWindow", "wrf"))
        self.pushButton_input_soil_folder.setText(_translate("MainWindow", "..."))
        self.label_5.setText(_translate("MainWindow", "input_soil"))
        self.pushButton_input_sounding_folder.setText(_translate("MainWindow", "..."))
        self.label_6.setText(_translate("MainWindow", "exe folder"))
        self.label_11.setText(_translate("MainWindow", "input folder"))
        self.label_9.setText(_translate("MainWindow", "wrf_out"))
        self.pushButton_wrf_out_folder.setText(_translate("MainWindow", "..."))
        self.pushButton_force_ideal_folder.setText(_translate("MainWindow", "..."))
        self.pushButton_wrf_folder.setText(_translate("MainWindow", "..."))
        self.label_13.setText(_translate("MainWindow", "output folder"))
        self.label_15.setText(_translate("MainWindow", "namelist_input"))
        self.pushButton_namelist_input_folder.setText(_translate("MainWindow", "..."))
        self.pushButton_run_scm_wrf.setText(_translate("MainWindow", "RUN WRF SCM"))
        self.label_18.setText(_translate("MainWindow", "wrf run log:"))
        self.pushButton_wrf_run_log_clear.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Run"))
        self.label_20.setText(_translate("MainWindow", "variable"))
        self.label_21.setText(_translate("MainWindow", "variable"))
        self.label_22.setText(_translate("MainWindow", "variable"))
        self.label_19.setText(_translate("MainWindow", "variable"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Result"))

from mplwidget import MplWidget
