# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(2596, 1660)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.initialization = QtWidgets.QGroupBox(self.tab)
        self.initialization.setObjectName("initialization")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.initialization)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.plot_initial_widget = MplWidget(self.initialization)
        self.plot_initial_widget.setObjectName("plot_initial_widget")
        self.gridLayout_4.addWidget(self.plot_initial_widget, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.initialization, 1, 0, 1, 1)
        self.froce_groupBox = QtWidgets.QGroupBox(self.tab)
        self.froce_groupBox.setObjectName("froce_groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.froce_groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.comboBox = QtWidgets.QComboBox(self.froce_groupBox)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_7.addWidget(self.comboBox, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.froce_groupBox)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 4, 2, 1, 1)
        self.plot_force_widget = MplWidget(self.froce_groupBox)
        self.plot_force_widget.setObjectName("plot_force_widget")
        self.gridLayout_7.addWidget(self.plot_force_widget, 5, 0, 1, 3)
        self.gridLayout_3.addWidget(self.froce_groupBox, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 2)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setRowStretch(1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWidget_namelist = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_namelist.setObjectName("tableWidget_namelist")
        self.tableWidget_namelist.setColumnCount(0)
        self.tableWidget_namelist.setRowCount(0)
        self.gridLayout_5.addWidget(self.tableWidget_namelist, 1, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_5.addWidget(self.textBrowser, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox_maxDoms = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_maxDoms.setObjectName("comboBox_maxDoms")
        self.horizontalLayout.addWidget(self.comboBox_maxDoms)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_Reset = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Reset.setObjectName("pushButton_Reset")
        self.horizontalLayout.addWidget(self.pushButton_Reset)
        self.pushButton_validate = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_validate.setObjectName("pushButton_validate")
        self.horizontalLayout.addWidget(self.pushButton_validate)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_5.setRowStretch(1, 9999)
        self.gridLayout_5.setRowStretch(2, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.log_textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.log_textBrowser.setEnabled(True)
        self.log_textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.log_textBrowser.setObjectName("log_textBrowser")
        self.gridLayout_6.addWidget(self.log_textBrowser, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.gridLayout_2.setRowStretch(0, 5)
        self.gridLayout_2.setRowStretch(1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.comboBox)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.initialization.setTitle(_translate("MainWindow", "input_souding_soil"))
        self.froce_groupBox.setTitle(_translate("MainWindow", "force_ideal.nc"))
        self.comboBox.setItemText(0, _translate("MainWindow", "U"))
        self.comboBox.setItemText(1, _translate("MainWindow", "V"))
        self.comboBox.setItemText(2, _translate("MainWindow", "W"))
        self.comboBox.setItemText(3, _translate("MainWindow", "QVAPOR"))
        self.comboBox.setItemText(4, _translate("MainWindow", "QCLOUD"))
        self.comboBox.setItemText(5, _translate("MainWindow", "QRAIN"))
        self.comboBox.setItemText(6, _translate("MainWindow", "theta"))
        self.label.setText(_translate("MainWindow", "variable:"))
        self.pushButton.setText(_translate("MainWindow", "column.xml"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Input"))
        self.label_2.setText(_translate("MainWindow", "Number of Domains(max_dom):"))
        self.pushButton_Reset.setText(_translate("MainWindow", "Reset"))
        self.pushButton_validate.setText(_translate("MainWindow", "Validate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "NameList"))
        self.groupBox.setTitle(_translate("MainWindow", "User Hint"))

from mplwidget import MplWidget
