# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(2500, 1800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.initialization = QtWidgets.QGroupBox(self.tab)
        self.initialization.setObjectName("initialization")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.initialization)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.plot_initial_widget = MplWidget(self.initialization)
        self.plot_initial_widget.setObjectName("plot_initial_widget")
        self.gridLayout_4.addWidget(self.plot_initial_widget, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.initialization, 1, 0, 1, 1)
        self.froce_groupBox = QtWidgets.QGroupBox(self.tab)
        self.froce_groupBox.setObjectName("froce_groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.froce_groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.comboBox = QtWidgets.QComboBox(self.froce_groupBox)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_7.addWidget(self.comboBox, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.froce_groupBox)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 4, 2, 1, 1)
        self.plot_force_widget = MplWidget(self.froce_groupBox)
        self.plot_force_widget.setObjectName("plot_force_widget")
        self.gridLayout_7.addWidget(self.plot_force_widget, 5, 0, 1, 3)
        self.gridLayout_3.addWidget(self.froce_groupBox, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 2)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setRowStretch(0, 1)
        self.gridLayout_3.setRowStretch(1, 10000)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.log_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_groupBox.sizePolicy().hasHeightForWidth())
        self.log_groupBox.setSizePolicy(sizePolicy)
        self.log_groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.log_groupBox.setMaximumSize(QtCore.QSize(2991, 16777215))
        self.log_groupBox.setObjectName("log_groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.log_groupBox)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.log_textBrowser = QtWidgets.QTextBrowser(self.log_groupBox)
        self.log_textBrowser.setMaximumSize(QtCore.QSize(2949, 16777215))
        self.log_textBrowser.setObjectName("log_textBrowser")
        self.horizontalLayout_4.addWidget(self.log_textBrowser)
        self.gridLayout_2.addWidget(self.log_groupBox, 2, 0, 1, 1)
        self.gridLayout_2.setRowStretch(0, 5)
        self.gridLayout_2.setRowStretch(2, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(MainWindow.parse_xml)
        self.comboBox.currentTextChanged['QString'].connect(MainWindow.on_force_combobox)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.log_textBrowser)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.initialization.setTitle(_translate("MainWindow", "input_souding_soil"))
        self.froce_groupBox.setTitle(_translate("MainWindow", "force_ideal.nc"))
        self.comboBox.setItemText(0, _translate("MainWindow", "U"))
        self.comboBox.setItemText(1, _translate("MainWindow", "V"))
        self.comboBox.setItemText(2, _translate("MainWindow", "W"))
        self.comboBox.setItemText(3, _translate("MainWindow", "QVAPOR"))
        self.comboBox.setItemText(4, _translate("MainWindow", "QCLOUD"))
        self.comboBox.setItemText(5, _translate("MainWindow", "QRAIN"))
        self.comboBox.setItemText(6, _translate("MainWindow", "theta"))
        self.label.setText(_translate("MainWindow", "variable:"))
        self.pushButton.setText(_translate("MainWindow", "column.xml"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Input"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "NameList"))
        self.log_groupBox.setTitle(_translate("MainWindow", "log"))

from mplwidget import MplWidget
